defmodule CatGenerator.Names do
  @moduledoc """
    Names for the cats
  """

  @names [
    "Agatha Christie",
    "Al Poochino",
    "Aladdin",
    "Alidoro",
    "Ann",
    "Augustus Octavian",
    "Bandi",
    "Bevis",
    "Big Boss",
    "Big Foot",
    "Bigun",
    "Bilbo Baggins",
    "Blackie",
    "Bliss",
    "Blowout",
    "Boatswain",
    "Bobo",
    "Bomber",
    "BooBoo",
    "Boomer",
    "Boots",
    "Bro",
    "Bubbles",
    "Buckaroo",
    "Bucko",
    "Buffin",
    "Bugsy",
    "Bullet",
    "Buster",
    "Butch",
    "Buzz",
    "Ca Cee",
    "Cadi",
    "Cally",
    "Candi",
    "Capoochino",
    "Cati",
    "Catpuccino",
    "Chaps",
    "Charlette",
    "Charlie",
    "Charmain",
    "Cherokee",
    "Chimpy",
    "Chris",
    "Chu Chen",
    "Chuckles",
    "Coco",
    "Codie",
    "Corker",
    "Cotton",
    "Cottontail",
    "Cowboy",
    "Crockett Cat",
    "D.C.",
    "Dagney",
    "Dar",
    "Digi",
    "Dinah",
    "Donald",
    "Donation",
    "Doo Dah",
    "Dough Boy",
    "Dude",
    "Duffie",
    "Euripides",
    "Farkle",
    "Ferret Fawcett",
    "Fluffer",
    "Flush",
    "Fraidy",
    "Ghillie",
    "Gi Gi",
    "Girl",
    "Goofie Bear",
    "Gorbe Chow",
    "Grammer",
    "Grendel",
    "Groovey",
    "Grrrr",
    "Halo",
    "Hazard",
    "Henry Wadsworth Longfellow",
    "Hester Prynne",
    "Hissy Fit",
    "Hojo",
    "Howie",
    "J.J.",
    "Jetta",
    "JIYA",
    "Jola",
    "Juana",
    "Julina",
    "Justene",
    "Kalynn",
    "Keys",
    "Keziah",
    "Kienan",
    "Kitter",
    "Kitty Carlyle",
    "Kivi",
    "Kukuq",
    "Laertes",
    "Landers",
    "Lar",
    "Lathrop",
    "Licia",
    "Lilah",
    "Locke",
    "LouEllen",
    "MacAlpin",
    "Markel",
    "Maryann",
    "Maura",
    "Megara",
    "Merewood",
    "Mertise",
    "Micah",
    "Minal",
    "Minninnewah",
    "Miss Muffet",
    "Miss Take",
    "Mister",
    "Misty",
    "Mitch",
    "Mo",
    "Modeste",
    "Mona",
    "Montaine",
    "Mooney",
    "Morna",
    "Ms.",
    "Muffin",
    "Muhunnad",
    "Mutt",
    "Myah",
    "Nora",
    "Oleander",
    "Pabla",
    "Paciencia",
    "Pandora",
    "Parisch",
    "Patrice",
    "Pee Dee",
    "Pegasus",
    "Penrod",
    "Philberta",
    "Pinky",
    "Pooky",
    "Popeye",
    "Priscilla",
    "Puddy Willow",
    "Puff",
    "Puppy",
    "Pura",
    "Purrsnickitty",
    "Puss Cat",
    "Pwyll",
    "Raanan",
    "Raul",
    "Redding",
    "Rhonda",
    "Ricky",
    "Robertia",
    "Romhilde",
    "Royal",
    "Rueban",
    "Rune",
    "Sativola",
    "Saumya",
    "Sceadu",
    "Shaelynn",
    "Sheena",
    "Shunnareh",
    "Siany",
    "Silvestre",
    "Sir Woody",
    "Sirius",
    "Siubhan",
    "Skitter",
    "Skwiggles",
    "Skyelar",
    "Snoozer",
    "Snuggles",
    "Sophia",
    "Sowingwa",
    "Splash",
    "Sprinkle",
    "Squat",
    "Stash or Moustache",
    "Sterling",
    "Stevan",
    "Stimpy",
    "Stormy",
    "Stray Cat",
    "Struana",
    "Sueanne",
    "Sugar",
    "Sumo",
    "T-Rex",
    "Tabby",
    "Tate",
    "Teague",
    "Thurmond",
    "Tiffanie",
    "Tillman",
    "Titia",
    "Tobin",
    "Too-Tall",
    "Tor",
    "Toran",
    "Travion",
    "Tuffy",
    "Tusche",
    "Voistitoevitz",
    "Waterford",
    "Whiz O",
    "Wicket",
    "Wild Child",
    "Willow",
    "Zac"
  ]

  def take(count), do: Enum.take_random(@names, count)
  def take_one(), do: @names |> Enum.take_random(1) |> List.first()
end